### ISSUE TITLE
missing bytes EOF

### ISSUE THREAD

**Issue by elbereth** [elbereth/DragonUnPACKer#14]
Ok here is the bug i found wich seems consistant with
WAV files i unpack from game files using hyperripper.
The last 4 bytes seem to be missing wich is causing 
playback and re-encoding problems as i try to 
manipulate the files. 
I have a more clear example below to show wich i got
using a hex editor to edit the original game file and
also the file i unpacked using DragonUnpacker.

opening the wav file i extracted with hyperripper in
a hexeditor i scrolled down to the bottom of it and 
seen this:
................LISTF...INFOICRD....2003-06-
23..IENG....Eric Brosius..ISFT....Sound Forge 

in the right hand coloum.

When i hexedited the origional wav and scrolled down 
this is what i got :

................LISTF...INFOICRD....2003-06-
23..IENG....Eric Brosius..ISFT....Sound Forge 4.5.

in the right hand coloum.

I compared the two wavs in hexeditor plus many other 
wavs i extracted and it seems that the last 4 bytes 
are always missing, causing a problem with the TRUE
length of the file in hex.
I have attached the 2 files for you to look at.
You can see from this example that they have a 
different length size in hex due to this problem of 
the 4 missing bytes.

Reported by: dezzy28

**Comment by linuxjackto1** [comment]
thanks www.movied.org
