### ISSUE TITLE
missing spec_DULK.pas

### ISSUE THREAD

**Issue by Halamix2** [elbereth/DragonUnPACKer#161]
/common/spec_DUL.pas is used by dlookd and dlookc tools but it's missing. 
Deleted in 5fc43b2d60303aa62595baa1bd1d60813d43b911
Last modification in 3375b0ede5cc6fc8cb150d1d373a47627208c98

**Comment by elbereth** [comment]
dlookc and dlookd are obsolete. Latest version don't use dulk files anymore.
