### ISSUE TITLE
Possibility to extract subdirectories with included files

### ISSUE THREAD

**Issue by kisonik** [elbereth/DragonUnPACKer#162]
I'd like possibility to extract subdirectories with included files, especially for Age of Empires .bar files.

**Comment by elbereth** [comment]
Don't know what more you need compared to what already exists... By right clicking on the folders on the left treeview.

![clipboard01](https://cloud.githubusercontent.com/assets/1632446/16541572/15061194-4044-11e6-8c11-69409d9e2863.png)

**Comment by kisonik** [comment]
This option extracts only subdirectories without files.

**Comment by elbereth** [comment]
Ah! I see. Regression introduced in 5.7.0.
Fixed in commit cee6a0a5db388f85083852699878554eb4d886bc
