### ISSUE TITLE
HyperRipper doesn't seem to be finding any files with offsets > 2GB

### ISSUE THREAD

**Issue by PJayB** [elbereth/DragonUnPACKer#164]
Hi,

I'm using HyperRipper to locate DDS files from very large pack file (25GB). I know that there are 1025 DDSs packed into the file at offsets spanning the entire range of the file. However, HyperRipper reports that there are only 134, and the log indicates the last one it found was at offset 0x7F7FE61A. The next DDS is beyond the 2GB boundary (0x80000000). 

HyperRipper does continue to scan the rest of the file, but no entries are found.

Thanks,
Pete

**Comment by elbereth** [comment]
Fixed in commit c23d6bc
