### ISSUE TITLE
elberethzone.net is unavailable due to DNSSEC error

### ISSUE THREAD

**Issue by pipboy96** [elbereth/DragonUnPACKer#180]
https://dnssec-debugger.verisignlabs.com/elberethzone.net

**Comment by Halamix2** [comment]
May it be cause of #174 ?

**Comment by pipboy96** [comment]
@Halamix2 Unlikely, the website was available back then.

**Comment by elbereth** [comment]
Fixed. Was in holidays for 2 weeks and had no access to the OpenDNSSEC server.
A simple service reboot fixed the problem (ods-signerd could not find the key in HSM...). It was up since early Mars.
Will add a cronjob to autorestart this service once in a while.

**Comment by pipboy96** [comment]
@elbereth Sorry for off-topic, but can you document your DNS setup, or at least tell me the HSM model you are using?
