### ISSUE TITLE
HyperRipper .WEBM Support

### ISSUE THREAD

**Issue by ThatOtterGuy** [elbereth/DragonUnPACKer#200]
I recently was trying to extract some animated sprites from a fan patch of a VN but it seems like the file format is unsupported by HyperRipper. I know they are there because I have used RPA Extractor. But the main reason why I have to use DragonUnpacker is because RPA Extractor will output corrupted files that can't be opened and have absurdly huge file sizes.

**Comment by elbereth** [comment]
Should be feasible, if I am able to compile a new version (Delphi 7 is very old...).

**Comment by elbereth** [comment]
Added in commit fe9f9a76f767fdf28c877b88dcc89ab7dfc1fccf.
You can check nigthly builds on https://www.elberethzone.net/en/dragon-unpacker-dev.html#download-nightly
