### ISSUE TITLE
"Send bug report to" window mentions SourceForge Tracker

### ISSUE THREAD

**Issue by halamix2** [elbereth/DragonUnPACKer#203]
- [ ] Redirect users to Github issues
![obraz](https://github.com/elbereth/DragonUnPACKer/assets/5176598/ba00de1a-dce7-45a5-8fdf-fb506a16e8ee)

**Comment by elbereth** [comment]
Fixed in commit dcbee6001d00635cdf277a34495249ef5469eb72.
See https://www.elberethzone.net/en/dragon-unpacker-dev.html#download-nightly for nightly builds.
